version: "3.8"

services:
    app:
        container_name: app
        build:
            context: ./php
            network: host
        networks:
            - network
        ports:
            - "9000:9000"
        volumes:
            - ./..:/var/www
            - ./php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www

    db:
        container_name: db
        image: mariadb:10.3.39
        cap_add:
            - SYS_NICE
        networks:
            - network
        environment:
            MYSQL_DATABASE: test_task_db
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: test_task_user
            MYSQL_PASSWORD: 123
        ports:
            - '3307:3306'
        volumes:
            - ./db_data:/var/lib/mysql
            - ./dumps:/docker-entrypoint-initdb.d
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        networks:
            - network
        volumes:
            - ./..:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - db
            - app

networks:
  network:
    driver: bridge
